### ISSUE TITLE
Allow backticked pipes (`|`) in tables

### ISSUE THREAD

**Issue by rauschma** [fcrespo82/vscode-markdown-table-formatter#1]
Love it, so far!

Issue: It doesn’t allow backticked pipes (`|`) in tables. For example:

Before:

```
| a        | b | c |
|:---------|:--|:--|
| fdasdfas | x `|` y | z |
```

After:

```
| a        | b   | c       |
|:---------|:----|:--------|
| fdasdfas | x ` | ` y | z |
```

**Comment by fcrespo82** [comment]
Closed by commit https://github.com/fcrespo82/vscode-markdown-table-formatter/commit/8c6c8e006883ac7aada7f515fdd1fbb90807aae1
