### ISSUE TITLE
Reorganize columns

### ISSUE THREAD

**Issue by fcrespo82** [fcrespo82/vscode-markdown-table-formatter#10]
Option to move columns around.

Should enter an edit mode?
Ask for column from and to?
Reorganize by column number? e.g.: 1,4,3,2

**Comment by rauschma** [comment]
Maybe that’s not necessary: multi-cursor cut&paste works quite well for moving columns.

**Comment by fcrespo82** [comment]
You don't think a feature like this would enhance the experience?
I'm falling to find a good way to implement it using the VSCode APIs, maybe I will drop this idea.
