### ISSUE TITLE
Configuration option for delimiter row padding

### ISSUE THREAD

**Issue by stephen-dexda** [fcrespo82/vscode-markdown-table-formatter#14]
Currently, the formatter doesn't pad the delimiter row:

`|:----|-----|:---:|----:|`

It would be nice to have this configurable, so it can be matched with a user's existing delimiter row style, e.g.:

"Space or alignment marker":

`|:--- | --- |:---:| ---:|`

"Single space always":

`| :-- | --- | :-: | --: |`

**Comment by fcrespo82** [comment]
Nice idea, I’ll add this to the v2.0 that I’m planing to release in the next weeks

**Comment by stephen-dexda** [comment]
Thanks a lot for this :) Couple of fixes needed:

* delimiterRowPadding missing from README.md.
* You've got a bit of copypasta in the title/description for the setting in package.json ;)

**Comment by fcrespo82** [comment]
Yep, still need some polishing before release, but the core of the function is ready.

**Comment by stephen-dexda** [comment]
Hey, just a heads-up, you've still got the last fixes missing from the 2.0.0 release on the marketplace.
