### ISSUE TITLE
Shortcuts for move column right/left conflict with standard "select word" shortcuts on macOS

### ISSUE THREAD

**Issue by stephen-dexda** [fcrespo82/vscode-markdown-table-formatter#16]
markdown-table-formatter.moveColumnLeft is mapped to <kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>LeftArrow</kbd>. However, <kbd>Alt</kbd>-<kbd>LeftArrow</kbd> means "move one word left" on macOS, so with <kbd>Shift</kbd>, it means "select one word to the left".

Similarly for markdown-table-formatter.moveColumnRight.

**Comment by fcrespo82** [comment]
This should be fixed in 2.0.2
