### ISSUE TITLE
Invalid count value

### ISSUE THREAD

**Issue by liangjiancang** [fcrespo82/vscode-markdown-table-formatter#19]
settings: { "markdown-table-formatter.delimiterRowPadding": "Follow Space Padding" }

try to format:

```md
a|c
-|-
c|d
```

=> Warning: Invalid count value

**Comment by fcrespo82** [comment]
I found the bug and fixed, but the formatting looks odd.

```
| a | b |
| -- | -- |
| c | d |
```

 Since 1 character header and lines are difficult to really use in real life I'm going to leave this as is for now but keep the issue open until I found a better way.
