### ISSUE TITLE
Shortcuts for move column right/left conflict with next/previous editor shortcuts on macOS

### ISSUE THREAD

**Issue by jlelong** [fcrespo82/vscode-markdown-table-formatter#25]
This is a follow-up on #16.

The `markdown-table-formatter.moveColumnLeft` command is mapped to `cmd+alt+left`, which is also the standard shortcut for _Next Editor_. I understand that it might be difficult to change the shortcut but maybe just changing `"when": "editorTextFocus"` to `"when": "editorTextFocus && editorLangId == 'markdown' " in https://github.com/fcrespo82/vscode-markdown-table-formatter/blob/master/package.json#L76 would already help.

The same problem arises for `markdown-table-formatter.moveColumnRight`.

**Comment by fcrespo82** [comment]
I understand you completely, I struggled to find a keyboard shortcut but couldn't. I know that is frustrating to have an extension override a native shortcut. I'll try to find an alternative, but if I fail I am more inclined to remove the shortcut and let the user decide.
