### ISSUE TITLE
Formatting removes indentation of tables

### ISSUE THREAD

**Issue by douglaswth** [fcrespo82/vscode-markdown-table-formatter#32]
If I have a table that is indented (for example: because it is part of a list):

```markdown
* Stuff:
  | One | Two | Three |
  | --- | --- | ----- |
  | `1` | `2` | `3`   |
```

> * Stuff:
>   | One | Two | Three |
>   | --- | --- | ----- |
>   | `1` | `2` | `3`   |

It gets incorrectly re-formatted to:

```markdown
* Stuff:
| One | Two | Three |
| --- | --- | ----- |
| `1` | `2` | `3`   |
```

> * Stuff:
> | One | Two | Three |
> | --- | --- | ----- |
> | `1` | `2` | `3`   |

Also, if the table starts on the same line as the list:

```markdown
* | One | Two | Three |
  | --- | --- | ----- |
  | `1` | `2` | `3`   |
```

> * | One | Two | Three |
>   | --- | --- | ----- |
>   | `1` | `2` | `3`   |

It gets incorrectly re-formatted to:

```markdown
| *   | One | Two | Three |
| --- | --- | --- | ----- |
| `1` | `2` | `3` |       |
```

> | *   | One | Two | Three |
> | --- | --- | --- | ----- |
> | `1` | `2` | `3` |       |

**Comment by fcrespo82** [comment]
Fixed in v2.2.0
