### ISSUE TITLE
Add an option to choose table separators spacing

### ISSUE THREAD

**Issue by aloeugene** [fcrespo82/vscode-markdown-table-formatter#33]
What I would like to propose is adding ability to have table separator to also be affected by the "How many spaces between left and right of each column content" setting.

*The default behavior right now is the following. If the setting is set to `1`, we don't have any padding:*

```
|------|------|------|
```

*What I would like it to be is the following:*

```
| ------ | ------ | ------ |
```

---

*It would be awesome to either have the existing option also affect that spacing or have another option that would control spacing of separators.*

**Comment by fcrespo82** [comment]
Did you try setting this setting delimiterRowPadding as "Follow Space Padding"?

```
"markdown-table-formatter.delimiterRowPadding": "Follow Space Padding"
```

**Comment by aloeugene** [comment]
Oh man, I completely missed that setting in the list...

Many thanks @fcrespo82 and sorry for redundant issue!!

**Comment by fcrespo82** [comment]
Not a problem. Glad It worked out for you.

Thanks for the feedback!
