### ISSUE TITLE
Numeric sort in tables

### ISSUE THREAD

**Issue by thisdavej** [fcrespo82/vscode-markdown-table-formatter#36]
I love the table sort feature!  A helpful enhancement would be if columns containing integers or floats could be sorted numerically rather than alphanumerically.  This would ensure a sort of `1, 2, 10` rather than `1, 10, 2`.

**Comment by fcrespo82** [comment]
This would be a great enhancement. I'll look into it.

**Comment by fcrespo82** [comment]
Thanks for the suggestion.

This should be up in [v2.1.4](https://github.com/fcrespo82/vscode-markdown-table-formatter/releases/tag/v2.1.4) and in [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=fcrespo82.markdown-table-formatter)

**Comment by thisdavej** [comment]
Wow - I downloaded the updated version it works fantastic with that numeric sort.  Fernando, thanks for creating this excellent extension and adding my feature request so quickly!

**Comment by goyalyashpal** [comment]
Commit: https://github.com/fcrespo82/vscode-markdown-table-formatter/commit/6d086d00da1c5e1465b96cc3c884405f96684290

( via tags: https://github.com/fcrespo82/vscode-markdown-table-formatter/commits/v2.1.4 )
