### ISSUE TITLE
First and last pipe are not kept when sorting

### ISSUE THREAD

**Issue by funnym0nk3y** [fcrespo82/vscode-markdown-table-formatter#40]
First and last pipe are not kept when sorting even though the option is enabled. 

**Versions**

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by fcrespo82** [comment]
Thanks for the feedback.

Will look into it asap.
