### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [fcrespo82/vscode-markdown-table-formatter#41]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by fcrespo82** [comment]
Hi @noraj !

Just published there https://open-vsx.org/extension/fcrespo82/markdown-table-formatter 

Thanks for the feedback and interest in my extension.

Just claimed the namespace too, to publish my other extensions there too. 

I will integrate publishing there automatically when the VSCode market place is updated.

**Comment by noraj** [comment]
Thank you for your reactivity, keep up the good work.
