### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by AdrianBinDC** [fcrespo82/vscode-markdown-table-formatter#48]
Can you post a quick example of how to use it that presumes the end user eats paste and crayons? #AskingForAFriend

What would be super helpful is example text on the plugin page in VSC that shows how to format and what buttons to press to get it to do its thing. Ex:

```
Header A | Header B | Header C
blah | blah | blah
```

> then, press some key sequence and it'll automagically it'll look like this:

```
Header A | Header B | Header C
blah     | blah     | blah
```

I was hoping I could highlight the stuff I want to turn into a table, press command + shift + p (on a Mac) and find a markdown table formatter command that'll format. The only thing I see is setting it for the current language.

**Comment by fcrespo82** [comment]
Try with:
```
Header A | Header B | Header C
-|-|-
blah | blah | blah
```

For the extension to understand its a table, it needs:
- A header row
- A formatting row
- At least data 1 row

Then it should format it to: 

```
| Header A | Header B | Header C |
|----------|----------|----------|
| blah     | blah     | blah     |
```

**Comment by AdrianBinDC** [comment]
Awesome! Thank you!!!
