### ISSUE TITLE
Support heading separator with Spaces/Tabs

### ISSUE THREAD

**Issue by irvnriir** [fcrespo82/vscode-markdown-table-formatter#50]
for a long time, i thought this Extension doesn't work .

because it doesn't support 1 of the most justified syntaxes:
```
| <<name>>	| <<name>>	| <<name>>
| ---		| ---		| ---
| <<value>>	| <<value>>	| <<value>>
```

plz make it: recognize this and keep when Formatting . also would be good if it would support Tabs for indenting the next column, but thats not as important .

also, i can't figure out how to use the sorting .

**Comment by fcrespo82** [comment]
Hi @irvnriir sorry for the long delay. I am the single developer of this extension and was caught in many other projects. I want to get back supporting, but I can't promise any timeframe. I identified that the divider row is using tabs instead of spaces, I could flexibilize the parser to include tabs, I'll see if I can without compromising other parts of the code. Thanks for the report.

**Comment by irvnriir** [comment]
@fcrespo82 Glad to hear . Im pretty sure this extension also doesn't support the space before the "---" , but i may be not recalling correctly .

**Comment by irvnriir** [comment]
Ty for the update .

Im usually always using the "---" , to make the syntax more unique across the whole storage .

`markdown-table-formatter.delimiterRowPadding`\Follow Space Padding

![image](https://github.com/fcrespo82/vscode-markdown-table-formatter/assets/13949704/74881ac7-7c70-4cee-aecf-17e909d5db0f)

Maybe you can add "---" option to the `.delimiterRowPadding` ? And maybe ability to limit the detection, to avoid the Code Lenses being added where shouldn't be ?

**Comment by fcrespo82** [comment]
I don't think I understand. Could you open another issue and elaborate more there?

**Comment by irvnriir** [comment]
@fcrespo82
The subject is an ability to set the Extension to output minimum 3 "-" for each the separator cell . It makes the tables more readable (because, for example, a value cell can have "-" and maybe even "--" as it's value) , and allows to copy/keep the tables to/in files which use languages which are using that more compatible Markdown syntax for tables . That feature is a part of the syntax i referred to, so seems to be a part of this Issue . I can create a new one if you still want it .
