### ISSUE TITLE
Sort - Ignore Case

### ISSUE THREAD

**Issue by goyalyashpal** [fcrespo82/vscode-markdown-table-formatter#53]
It would be nice if sort could ignore the Case while Sorting.

I just used this awesome FOSS extension of urs to move columns & sort from this markdown table (~160 rows - massive for me in context of markdown tables) of Jupyter-kernels - and woah, it worked so fast & brilliantly. Now i have one less reason to use the Typora Markdown Editor

https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

* The capital letter was being placed ahead of small letter (likely ASCII) - I got around it by Making first letter capital of all offenders.
* But it still tripped me where whole word had different cases: `MATLAB` vs `Matlab`

There was one more offender reason - the `[` opening square bracket symbol in front of letters - though, this was pretty simple to overcome - as i just removed it & sorted again - then added `[` it back.

**Comment by fcrespo82** [comment]
Hi @goyalyashpal, thanks for your suggestion. I don't know if I can treat the `[` in front of letters, it would be an extremely specific case, but offering the option to sort case insensitive is a good one.

**Comment by goyalyashpal** [comment]
> [leading `[`] would be an extremely specific case

yep, i totally agree with this.

thanks a lot for provising such an awesome tool as FOSS again.
