### ISSUE TITLE
Add "sort" in actions - available via command palette

### ISSUE THREAD

**Issue by goyalyashpal** [fcrespo82/vscode-markdown-table-formatter#54]
The implementation for which column to sort according to - can be similar to how which column to move left/right is decided.

i.e. the column in which cursor currently is (ref: https://github.com/fcrespo82/vscode-markdown-table-formatter/issues/10#issuecomment-549539479)

also, it would be nice to have an action for refresh sort. so that the currently chosen sort (whether ascending or descending) is applied again - rather than requiring toggle twice.

**Comment by fcrespo82** [comment]
Hi @goyalyashpal, thanks for your suggestion I want to update this extension with some improvements that were suggested by the users. I can't promise a timeframe, but I should add this in the batch.
