### ISSUE TITLE
Repeat character inserted at end of table on format

### ISSUE THREAD

**Issue by droberts-ada** [fcrespo82/vscode-markdown-table-formatter#6]
![table_formatter_extra_character](https://user-images.githubusercontent.com/21064499/51957869-28874900-2402-11e9-9827-5bb56d1f1219.gif)

I can only reproduce when "Keep First And Last Pipes" is disabled, and "Limit Last Column Padding" is enabled. Seems that these two don't play nice together.

My settings:
![image](https://user-images.githubusercontent.com/21064499/51957798-f0800600-2401-11e9-91e7-b415d4d25ff6.png)

**Comment by droberts-ada** [comment]
Hmmm, I can also sometimes repro this when "Limit Last Column Padding" is disabled.

**Comment by fcrespo82** [comment]
I was able to reproduce this bug.
Will look into it asap!

**Comment by droberts-ada** [comment]
Yep, seems to be fixed. Thanks for such a snappy response!
