### ISSUE TITLE
Sort table lines

### ISSUE THREAD

**Issue by fcrespo82** [fcrespo82/vscode-markdown-table-formatter#8]
Function to sort table lines

- [x] Needs #9 first

Core funcionality done. Test sort algorithms to have the most performance.

**Comment by goyalyashpal** [comment]
Commit history: 
https://github.com/fcrespo82/vscode-markdown-table-formatter/commits/v2.1.0?after=560c975ac1fa5a64bf99dee4a500ded5b0c5836d+104&branch=v2.1.0&qualified_name=refs%2Ftags%2Fv2.1.0
